#cloud-config
rancher:
  console: ubuntu
  docker: 
    engine: docker-19.03.4
  environment:
    EXTRA_CMDLINE: /init
  services-include:
    open-vm-tools: true
  state:
    autoformat:
    - /dev/sda
    - /dev/vda
    dev: LABEL=RANCHER_STATE
    wait: true
ssh_authorized_keys: []
runcmd:
  - "sudo apt update"
  - "sudo apt install -y open-iscsi"
  - "sudo sed -i 's_^iscsid.startup = /bin/systemctl start iscsid.socket_#iscsid.startup = /bin/systemctl start iscsid.socket_' /etc/iscsi/iscsid.conf"
  - "sudo sed -i 's_^# iscsid.startup = /sbin/iscsid_iscsid.startup = /sbin/iscsid_' /etc/iscsi/iscsid.conf"
  